name: Build and release edge builds

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    container:
      image: rust:1-buster
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: target/debug
          key: ${{ runner.os }}-cargo-${{ hashFiles(format('{0}{1}', github.workspace, '/Cargo.lock')) }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install Dependencies
        run: |
          apt-get update -y
          apt-get install build-essential libssl-dev llvm-dev libclang-dev -y
          rustup update
          rustup component add clippy
      - name: Lint code
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        run: cargo test
  container-image:
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    steps:
      - uses: actions/checkout@v1
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/matteojoliveau/apicurio-sync:${{ github.sha }}
  linux-binary:
    runs-on: ubuntu-latest
    needs: [ lint-and-test ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: target/debug
          key: ${{ runner.os }}-cargo-${{ hashFiles(format('{0}{1}', github.workspace, '/Cargo.lock')) }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install Dependencies
        run: |
          apt-get update -y
          apt-get install build-essential libssl-dev llvm-dev libclang-dev -y
          rustup update
      - name: Build
        run: cargo build --release --all-features
      - uses: 'actions/upload-artifact@v2'
        with:
          name: apicurio-sync-${{ runner.os }}
          path: ${{ github.workspace }}/target/release/apicurio-sync
